name: simple

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

releases:
- name: simple-release
  version: latest

update:
  canaries: 1
  canary_watch_time: 10000-600000
  update_watch_time: 10000-600000
  max_in_flight: 1
  serial: true

instance_groups:
- name: netcat
  instances: 1
  azs: [z1]
  networks:
  - name: simple
  vm_type: default
  stemcell: default
  jobs: []
